/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DIVISASPROG 0x20000099
#define DIVISASVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETUSD 1
extern  char ** getusd_1(int *, CLIENT *);
extern  char ** getusd_1_svc(int *, struct svc_req *);
#define GETEURO 1
extern  char ** geteuro_1(int *, CLIENT *);
extern  char ** geteuro_1_svc(int *, struct svc_req *);
#define GETYEN 1
extern  char ** getyen_1(int *, CLIENT *);
extern  char ** getyen_1_svc(int *, struct svc_req *);
extern int divisasprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETUSD 1
extern  char ** getusd_1();
extern  char ** getusd_1_svc();
#define GETEURO 1
extern  char ** geteuro_1();
extern  char ** geteuro_1_svc();
#define GETYEN 1
extern  char ** getyen_1();
extern  char ** getyen_1_svc();
extern int divisasprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
